### ISSUE TITLE
trying to use this with KMS enabled in SSM

### ISSUE THREAD

**Issue by jamengual** [claranet/sshm#2] opened 2020-01-02 23:02 UTC
Session manager is fully working with SSM when using the console.

when trying to use sshm I get 👍 
```
Encountered error while initiating handshake. KMSEncryption failed on client with status 2 error: Failed to process action KMSEncryption: Error calling KMS GenerateDataKey API: ValidationException: Invalid EncryptionContext
	status code: 400, request id: 412c6f32-xxxxx
```
I made sure I have access to the key etc by encrypting and decrypting files using that key, so it is not a key IAM access issue.

do you have any ideas?

**Comment by Issif** [comment] 2020-01-02 23:21
Do you faced same issue while trying with official AWS cli? 

https://docs.aws.amazon.com/cli/latest/reference/ssm/start-session.html

I'm trying to locate where the issue is.

**Comment by jamengual** [comment] 2020-01-02 23:30
I do not have that problem using the cli : 

```aws-vault exec stage -- aws ssm start-session --target i-XXXXXXXXX                                                                                                                   14.6s  Thu  2 Jan 15:28:57 2020

Starting session with SessionId: 1578007741979166000-085e9ab7ead02023a
This session is encrypted using AWS KMS.
sh-4.2$ hostname
```

**Comment by Issif** [comment] 2020-01-03 14:14
I don't use KMS with SSM and I don't see any related input in SDK. How do you select the keyId you use?

Can you tell me what version of `session-manager-plugin` you use please.

**Comment by Issif** [comment] 2020-01-03 15:49
I was able to reproduce, for know, I've no idea how to fix it. The issue appears when sshm calls `session-manager-plugin`.

**Comment by Issif** [comment] 2020-01-03 16:31
\o/

```
$ go run main.go -i i-XXXX

Starting session with SessionId: 1578068572765549500-07b33586751149944
This session is encrypted using AWS KMS.
```

I released [1.2.0](https://github.com/claranet/sshm/releases/tag/1.2.0), it should be ok for you now.

**Comment by jamengual** [comment] 2020-01-03 17:58
just updated it and it worked!!!

what was it?

**Comment by Issif** [comment] 2020-01-03 18:18
`session-manager-plugin` is a total black box, no documentation, no help command and even no public sources. I checked in `aws-cli` sources how it is called and see I forgot an input. I can't explain why it worked before.

**Closed as completed by Issif** 2020-01-03 18:18 UTC
